#include <stdio.h>
#include "hocdec.h"
#define IMPORT extern __declspec(dllimport)
IMPORT int nrnmpi_myid, nrn_nobanner_;

extern void _ANsyn_reg();
extern void _IA_reg();
extern void _Ih_reg();
extern void _Kaxon_reg();
extern void _Kdend_reg();
extern void _Ksoma_reg();
extern void _LcaMig_reg();
extern void _Naaxon_reg();
extern void _Nadend_reg();
extern void _Nasoma_reg();
extern void _STDPE2Syn_reg();
extern void _bgka_reg();
extern void _burststim2_reg();
extern void _cad_reg();
extern void _cagk_reg();
extern void _cal_reg();
extern void _calH_reg();
extern void _car_reg();
extern void _cat_reg();
extern void _ccanl_reg();
extern void _gskch_reg();
extern void _h_reg();
extern void _hNa_reg();
extern void _hha2_reg();
extern void _hha_old_reg();
extern void _ichan2_reg();
extern void _kad_reg();
extern void _kap_reg();
extern void _kca_reg();
extern void _km_reg();
extern void _my_exp2syn_reg();
extern void _nca_reg();
extern void _nmda_reg();
extern void _regn_stim_reg();
extern void _somacar_reg();
extern void _vecevent_reg();

modl_reg(){
	//nrn_mswindll_stdio(stdin, stdout, stderr);
    if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
	fprintf(stderr, "Additional mechanisms from files\n");

fprintf(stderr," ANsyn.mod");
fprintf(stderr," IA.mod");
fprintf(stderr," Ih.mod");
fprintf(stderr," Kaxon.mod");
fprintf(stderr," Kdend.mod");
fprintf(stderr," Ksoma.mod");
fprintf(stderr," LcaMig.mod");
fprintf(stderr," Naaxon.mod");
fprintf(stderr," Nadend.mod");
fprintf(stderr," Nasoma.mod");
fprintf(stderr," STDPE2Syn.mod");
fprintf(stderr," bgka.mod");
fprintf(stderr," burststim2.mod");
fprintf(stderr," cad.mod");
fprintf(stderr," cagk.mod");
fprintf(stderr," cal.mod");
fprintf(stderr," calH.mod");
fprintf(stderr," car.mod");
fprintf(stderr," cat.mod");
fprintf(stderr," ccanl.mod");
fprintf(stderr," gskch.mod");
fprintf(stderr," h.mod");
fprintf(stderr," hNa.mod");
fprintf(stderr," hha2.mod");
fprintf(stderr," hha_old.mod");
fprintf(stderr," ichan2.mod");
fprintf(stderr," kad.mod");
fprintf(stderr," kap.mod");
fprintf(stderr," kca.mod");
fprintf(stderr," km.mod");
fprintf(stderr," my_exp2syn.mod");
fprintf(stderr," nca.mod");
fprintf(stderr," nmda.mod");
fprintf(stderr," regn_stim.mod");
fprintf(stderr," somacar.mod");
fprintf(stderr," vecevent.mod");
fprintf(stderr, "\n");
    }
_ANsyn_reg();
_IA_reg();
_Ih_reg();
_Kaxon_reg();
_Kdend_reg();
_Ksoma_reg();
_LcaMig_reg();
_Naaxon_reg();
_Nadend_reg();
_Nasoma_reg();
_STDPE2Syn_reg();
_bgka_reg();
_burststim2_reg();
_cad_reg();
_cagk_reg();
_cal_reg();
_calH_reg();
_car_reg();
_cat_reg();
_ccanl_reg();
_gskch_reg();
_h_reg();
_hNa_reg();
_hha2_reg();
_hha_old_reg();
_ichan2_reg();
_kad_reg();
_kap_reg();
_kca_reg();
_km_reg();
_my_exp2syn_reg();
_nca_reg();
_nmda_reg();
_regn_stim_reg();
_somacar_reg();
_vecevent_reg();
}
